config/routes.rb
TaxesForCaitlin::Application.routes.draw do
  resources :expense_sources


  resources :income_methods


  resources :expense_items


  resources :income_items


  resources :expense_categories


  resources :income_categories


  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'finances_report', :to => 'pdf#finances_report'

  root :to => 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :username, :password, :password_confirmation, :first_name, :last_name, :email
	has_secure_password
	validates :username, presence: true
	validates :first_name, presence: true
	validates :last_name, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper
	before_filter :set_user
	def show
		@income_items = IncomeItem.where(:user_id => current_user.id)
		@expense_items = ExpenseItem.where(:user_id => current_user.id)
		@expense_categories = ExpenseCategory.where(:user_id => current_user.id)
	end

	def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
    		render "edit"
      end
    end
  end

	private

	def set_user
		@user = current_user
	end

end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password_confirmation, :class => 'password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary', :value => "Go!" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="text-center">
  <div class="box expense text-center">
    <h4><%= link_to "Expenses", expense_items_path %></h4>
    <hr>
    <table class='text-left'>
    <% @expense_categories.each do |e| %>
        <tr>
          <td><%= e.category_name %></td>
          <td>&nbsp;&nbsp;</td>
          <td><%= e.total %></td>
      <% end %>
    </table>
  </div>
  <div class="box income text-center">
    <h4><%= link_to "Income", income_items_path %></h4>
    <hr>
  </div>
  <div class="box overview text-center">
    <h4><%= link_to "Overview", income_items_path %></h4>
    <hr>
  </div>
</div>
<div style="height:35px">&nbsp;</div>
<div class="text-center">
  <span>Change scope:</span>
  <%= form_tag @path, method: :get do %>
    <%= text_field_tag :start_date, nil, :placeholder => "start date: YYYY-MM-DD", :width => "100" %>
    <%= text_field_tag :end_date, nil, :placeholder => "end date: YYYY-MM-DD", :width => "100" %>
    <%= submit_tag "Show", class: 'btn btn-mini' %><div class="box-container text-center">
    <% end %>
</div>