config/routes.rb
TaxesForCaitlin::Application.routes.draw do
  resources :expense_sources


  resources :income_methods


  resources :expense_items


  resources :income_items


  resources :expense_categories


  resources :income_categories


  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'finances_report', :to => 'pdf#finances_report'

  root :to => 'sessions#new'
end

app/models/income_category.rb
class IncomeCategory < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/income_categories_controller.rb
class IncomeCategoriesController < ApplicationController
  # GET /income_categories
  # GET /income_categories.json
  def index
    @income_categories = IncomeCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @income_categories }
    end
  end

  # GET /income_categories/1
  # GET /income_categories/1.json
  def show
    @income_category = IncomeCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @income_category }
    end
  end

  # GET /income_categories/new
  # GET /income_categories/new.json
  def new
    @income_category = IncomeCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @income_category }
    end
  end

  # GET /income_categories/1/edit
  def edit
    @income_category = IncomeCategory.find(params[:id])
  end

  # POST /income_categories
  # POST /income_categories.json
  def create
    @income_category = IncomeCategory.new(params[:income_category])

    respond_to do |format|
      if @income_category.save
        format.html { redirect_to @income_category, notice: 'Income category was successfully created.' }
        format.json { render json: @income_category, status: :created, location: @income_category }
      else
        format.html { render action: "new" }
        format.json { render json: @income_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /income_categories/1
  # PUT /income_categories/1.json
  def update
    @income_category = IncomeCategory.find(params[:id])

    respond_to do |format|
      if @income_category.update_attributes(params[:income_category])
        format.html { redirect_to @income_category, notice: 'Income category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @income_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /income_categories/1
  # DELETE /income_categories/1.json
  def destroy
    @income_category = IncomeCategory.find(params[:id])
    @income_category.destroy

    respond_to do |format|
      format.html { redirect_to income_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/income_categories_helper.rb
module IncomeCategoriesHelper
end

app/views/income_categories/_form.html.erb
<%= form_for @income_category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :category_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                income_categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/income_categories/edit.html.erb
<%- model_class = IncomeCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/income_categories/index.html.erb
<%- model_class = IncomeCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:category_name) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @income_categories.each do |income_category| %>
      <tr>
        <td><%= link_to income_category.id, income_category_path(income_category) %></td>
        <td><%= income_category.category_name %></td>
        <td><%= income_category.user_id %></td>
        <td><%=l income_category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_income_category_path(income_category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      income_category_path(income_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_income_category_path,
            :class => 'btn btn-primary' %>

app/views/income_categories/new.html.erb
<%- model_class = IncomeCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/income_categories/show.html.erb
<%- model_class = IncomeCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:category_name) %>:</strong></dt>
  <dd><%= @income_category.category_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @income_category.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              income_categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_income_category_path(@income_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              income_category_path(@income_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>