config/routes.rb
TaxesForCaitlin::Application.routes.draw do
  resources :expense_sources


  resources :income_methods


  resources :expense_items


  resources :income_items


  resources :expense_categories


  resources :income_categories


  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'finances_report', :to => 'pdf#finances_report'

  root :to => 'sessions#new'
end

app/models/expense_item.rb
class ExpenseItem < ActiveRecord::Base
  attr_accessible :date, :item, :expense_source_id, :amount, :comment, :user_id, :expense_category_id
  belongs_to :expense_category
end

app/controllers/expense_items_controller.rb
class ExpenseItemsController < ApplicationController
  # GET /expense_items
  # GET /expense_items.json
  def index
    @expense_items = ExpenseItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expense_items }
    end
  end

  # GET /expense_items/1
  # GET /expense_items/1.json
  def show
    @expense_item = ExpenseItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense_item }
    end
  end

  # GET /expense_items/new
  # GET /expense_items/new.json
  def new
    @expense_item = ExpenseItem.new
    @source_array = ExpenseSource.where(:user_id => current_user.id).map { |source| ["#{source.source}", source.id] }
    p "*"*80
    p @source_array
    @category_array = ExpenseCategory.where(:user_id => current_user.id).map { |category| ["#{category.category_name}", category.id] }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense_item }
    end
  end

  # GET /expense_items/1/edit
  def edit
    @expense_item = ExpenseItem.find(params[:id])
  end

  # POST /expense_items
  # POST /expense_items.json
  def create
    p "&"*80
    p params
    @expense_item = ExpenseItem.new(params[:expense_item])

    respond_to do |format|
      if @expense_item.save
        format.html { redirect_to @expense_item, notice: 'Expense item was successfully created.' }
        format.json { render json: @expense_item, status: :created, location: @expense_item }
      else
        format.html { render action: "new" }
        format.json { render json: @expense_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expense_items/1
  # PUT /expense_items/1.json
  def update
    @expense_item = ExpenseItem.find(params[:id])

    respond_to do |format|
      if @expense_item.update_attributes(params[:expense_item])
        format.html { redirect_to @expense_item, notice: 'Expense item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expense_items/1
  # DELETE /expense_items/1.json
  def destroy
    @expense_item = ExpenseItem.find(params[:id])
    @expense_item.destroy

    respond_to do |format|
      format.html { redirect_to expense_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/expense_items_helper.rb
module ExpenseItemsHelper
end

app/views/expense_items/_form.html.erb
<%= form_for @expense_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => "date_select" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :item, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :item, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expense_category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:expense_category_id, @category_array, {:include_blank => 'Select a category'}) %><br/>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expense_source_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:expense_source_id, @source_array, {:include_blank => 'Select a source'}) %><br/>  <br>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :comment, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                expense_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/expense_items/edit.html.erb
<%- model_class = ExpenseItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/expense_items/index.html.erb
<%- model_class = ExpenseItem -%>
<div class='text-right'>
  <%= link_to "Expense Categories", new_expense_category_path %> | 
  <%= link_to "Expense Sources", new_expense_source_path %>
</div>

<% if flash[:notice] %>
  <h4 class='flash'><%= flash[:notice] %></h4>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:expense_category_id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:expense_source_id) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @expense_items.each do |expense_item| %>
      <tr>
        <td><%= expense_item.date %></td>
        <td><%= expense_item.item %></td>
        <td><%= expense_item.expense_category_id %></td>
        <td><%= expense_item.amount %></td>
        <td><%= expense_item.expense_source_id %></td>
        <td><%= expense_item.comment %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_expense_item_path(expense_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      expense_item_path(expense_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_expense_item_path,
            :class => 'btn btn-primary' %>

app/views/expense_items/new.html.erb
<%- model_class = ExpenseItem -%>
<%= render :partial => 'form' %>

app/views/expense_items/show.html.erb
<%- model_class = ExpenseItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @expense_item.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= @expense_item.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expense_category_id) %>:</strong></dt>
  <dd><%= @expense_item.expense_category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @expense_item.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expense_source_id) %>:</strong></dt>
  <dd><%= @expense_item.expense_source_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @expense_item.comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @expense_item.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              expense_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_expense_item_path(@expense_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              expense_item_path(@expense_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>