config/routes.rb
TaxesForCaitlin::Application.routes.draw do
  resources :expense_sources


  resources :income_methods


  resources :expense_items


  resources :income_items


  resources :expense_categories


  resources :income_categories


  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'finances_report', :to => 'pdf#finances_report'

  root :to => 'sessions#new'
end

app/models/income_item.rb
class IncomeItem < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/income_items_controller.rb
class IncomeItemsController < ApplicationController
  # GET /income_items
  # GET /income_items.json
  def index
    @income_items = IncomeItem.where(:user_id => current_user.id).order(params[:sort])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @income_items }
    end
  end

  # GET /income_items/1
  # GET /income_items/1.json
  def show
    @income_item = IncomeItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @income_item }
    end
  end

  # GET /income_items/new
  # GET /income_items/new.json
  def new
    @income_item = IncomeItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @income_item }
    end
  end

  # GET /income_items/1/edit
  def edit
    @income_item = IncomeItem.find(params[:id])
  end

  # POST /income_items
  # POST /income_items.json
  def create
    @income_item = IncomeItem.new(params[:income_item])

    respond_to do |format|
      if @income_item.save
        format.html { redirect_to @income_item, notice: 'Income item was successfully created.' }
        format.json { render json: @income_item, status: :created, location: @income_item }
      else
        format.html { render action: "new" }
        format.json { render json: @income_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /income_items/1
  # PUT /income_items/1.json
  def update
    @income_item = IncomeItem.find(params[:id])

    respond_to do |format|
      if @income_item.update_attributes(params[:income_item])
        format.html { redirect_to @income_item, notice: 'Income item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @income_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /income_items/1
  # DELETE /income_items/1.json
  def destroy
    @income_item = IncomeItem.find(params[:id])
    @income_item.destroy

    respond_to do |format|
      format.html { redirect_to income_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/income_items_helper.rb
module IncomeItemsHelper
end

app/views/income_items/_form.html.erb
<%= form_for @income_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'date_select', :placeholder => "YYYY-MM-DD" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :item, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :item, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :income_category_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :income_category_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :income_method_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :income_method_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comment, :class => 'text_field' %>
    </div>
  </div>
    <div class="controls">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                income_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/income_items/edit.html.erb
<%- model_class = IncomeItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/income_items/index.html.erb
<%- model_class = IncomeItem -%>
<div class='text-right'>
  <%= link_to "Income Categories", new_income_category_path %> | 
  <%= link_to "Income Methods", new_income_method_path %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= link_to "Date", :sort => "date" %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th>Category</th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th>Method</th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @income_items.each do |income_item| %>
      <tr>
        <td><%= income_item.date %></td>
        <td><%= income_item.item %></td>
        <td><%= income_item.income_category.category_name %></td>
        <td><%= income_item.amount %></td>
        <td><%= income_item.income_method.method %></td>
        <td><%= income_item.comment %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_income_item_path(income_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      income_item_path(income_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_income_item_path,
            :class => 'btn btn-primary' %>

app/views/income_items/new.html.erb
<%- model_class = IncomeItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/income_items/show.html.erb
<%- model_class = IncomeItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @income_item.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= @income_item.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:income_category_id) %>:</strong></dt>
  <dd><%= @income_item.income_category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @income_item.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:income_method_id) %>:</strong></dt>
  <dd><%= @income_item.income_method_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @income_item.comment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @income_item.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              income_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_income_item_path(@income_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              income_item_path(@income_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>